import { DM_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header.jsx";

const dmSans = DM_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Hoppe E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={dmSans.className}>
        <Header />

        {children}
      </body>
    </html>
  );
}
