import { DM_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header.jsx";
import { getShopInfo } from "@/utils/globalApi.js";
import Container from "@/components/container/Container";
import Footer from "@/components/footer/Footer";

const dmSans = DM_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Hoppe E-Commerce",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const shopInfo = await getShopInfo();
  const logo = shopInfo.logo;
  const logoImage = `${process.env.NEXT_PUBLIC_BASE_URL}${logo.url}`;
  return (
    <html lang="en">
      <body className={dmSans.className}>
        <Header logoImage={logoImage} appName={shopInfo.name} />

        {children}
        <Container>
          <Footer shopInfo={shopInfo} />
        </Container>
      </body>
    </html>
  );
}
